### ISSUE TITLE
Broken overlays and no pits at Wheatley

### ISSUE THREAD

**Issue by DarkGradient** [PortalRex/portal2coopsp#2]
Hello. I found several flaws in your mod. 1 - Not all overlays are displayed correctly (or rather, they are not fully stretched).
Some of Wheatley's cameras lack gameplay elements like Pits.
And There is no music on some maps.  
If you can give me the map sources i can help you fix issuses
Screenshots if needed.
![image](https://user-images.githubusercontent.com/82389028/122639168-17961a00-d11a-11eb-9fa1-cb43f3129791.png)
![image](https://user-images.githubusercontent.com/82389028/122639236-9b500680-d11a-11eb-9899-ce4683b8ffe2.png)

**Comment by PortalRex** [comment]
My apologies I somehow completely missed this issue being both opened and closed. All of the VMF files are on the repo and can be downloaded. It should be noted that this mod was thrown together extremely quickly, about a week or twos effort was put into it and not much since.
